In [1]:
import numpy as np 
import pandas as pd 

from sklearn import datasets, linear_model 
from sklearn.metrics import mean_squared_error, r2_score 
from sklearn.model_selection import train_test_split
import statsmodels.api as sm

# Inbound Prediction

data process

In [2]:
# 總資料
data = pd.read_excel('data.xlsx')

In [3]:
# 預測資料
Year= int(input("預測年份："))
Month = int(input("預測月份："))

data_predict = data[(data['Year'] == Year) & (data['Month'] == Month)]
data_predict = data_predict.drop(['Inbound'], axis=1).reset_index(drop = True)

預測年份：2020
預測月份：4

In [4]:
# 訓練資料
data_train = data[data['Inbound'].notnull()]

In [5]:
# https://stackoverflow.com/questions/50733014/linear-regression-with-dummy-categorical-variables
# 很好用

# Model

In [6]:
from statsmodels.formula.api import ols

In [7]:
model = ols('Inbound ~ C(Year) + C(Month) + C(Weekday) + C(Bank) + C(Credit) + C(Vacation) + C(Period) + C(ChineseNY)', data = data_train).fit()

In [8]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Inbound   R-squared:                       0.772
Model:                            OLS   Adj. R-squared:                  0.753
Method:                 Least Squares   F-statistic:                     40.42
Date:                Fri, 05 Jun 2020   Prob (F-statistic):           2.96e-90
Time:                        10:04:28   Log-Likelihood:                -2463.5
No. Observations:                 364   AIC:                             4985.
Df Residuals:                     335   BIC:                             5098.
Df Model:                          28
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          2934.9065     73.161     40.115      0.000    2790.993    3078.820
C(Year)[T.2019]    -142.5348     47.408     -3.007      0.003    -235.791     -49.279
C(Year)[T.2020]    -477.4636     57.960     -8.238      0.000    -591.475    -363.452
C(Month)[T.2]      -116.7247     57.593     -2.027      0.043    -230.014      -3.435
C(Month)[T.3]      -128.2832     49.987     -2.566      0.011    -226.611     -29.955
C(Month)[T.4]      -146.0955     51.049     -2.862      0.004    -246.512     -45.679
C(Month)[T.5]      -207.9097     50.001     -4.158      0.000    -306.266    -109.554
C(Month)[T.6]      -392.6765     63.394     -6.194      0.000    -517.376    -267.977
C(Month)[T.7]      -408.3573     60.690     -6.729      0.000    -527.740    -288.975
C(Month)[T.8]      -240.0088     62.468     -3.842      0.000    -362.887    -117.130
C(Month)[T.10]     -234.8432     78.969     -2.974      0.003    -390.182     -79.505
C(Month)[T.11]     -485.8917     56.588     -8.586      0.000    -597.205    -374.578
C(Month)[T.12]     -259.1953     55.976     -4.631      0.000    -369.303    -149.088
C(Weekday)[T.2]    -244.2995     38.258     -6.386      0.000    -319.555    -169.044
C(Weekday)[T.3]    -275.6970     38.632     -7.136      0.000    -351.689    -199.705
C(Weekday)[T.4]    -405.0544     37.673    -10.752      0.000    -479.159    -330.949
C(Weekday)[T.5]    -430.2711     38.542    -11.164      0.000    -506.086    -354.456
C(Weekday)[T.6]   -1010.6697    105.783     -9.554      0.000   -1218.753    -802.586
C(Weekday)[T.7]    -881.1930    233.569     -3.773      0.000   -1340.639    -421.747
C(Bank)[T.1]         10.2092     35.817      0.285      0.776     -60.246      80.664
C(Bank)[T.2]        113.4510     35.849      3.165      0.002      42.933     183.969
C(Bank)[T.3]         12.2621     36.573      0.335      0.738     -59.679      84.203
C(Credit)[T.1]       93.4474     35.445      2.636      0.009      23.725     163.170
C(Credit)[T.2]      147.1671     36.282      4.056      0.000      75.798     218.536
C(Credit)[T.3]       76.3762     36.397      2.098      0.037       4.781     147.971
C(Vacation)[T.1]    449.1056     71.627      6.270      0.000     308.210     590.001
C(Period)[T.2]      -65.5218     29.847     -2.195      0.029    -124.232      -6.811
C(Period)[T.3]     -118.0364     30.519     -3.868      0.000    -178.069     -58.004
C(ChineseNY)[T.1] -1418.2135     89.824    -15.789      0.000   -1594.903   -1241.524
==============================================================================
Omnibus:                       45.908   Durbin-Watson:                   1.280
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              227.355
Skew:                           0.359   Prob(JB):                     4.27e-50
Kurtosis:                       6.804   Cond. No.                         30.1
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [9]:
# parameters

In [10]:
model.params

Intercept            2934.906483
C(Year)[T.2019]      -142.534818
C(Year)[T.2020]      -477.463580
C(Month)[T.2]        -116.724684
C(Month)[T.3]        -128.283227
C(Month)[T.4]        -146.095513
C(Month)[T.5]        -207.909675
C(Month)[T.6]        -392.676548
C(Month)[T.7]        -408.357254
C(Month)[T.8]        -240.008764
C(Month)[T.10]       -234.843239
C(Month)[T.11]       -485.891707
C(Month)[T.12]       -259.195324
C(Weekday)[T.2]      -244.299542
C(Weekday)[T.3]      -275.696980
C(Weekday)[T.4]      -405.054380
C(Weekday)[T.5]      -430.271149
C(Weekday)[T.6]     -1010.669677
C(Weekday)[T.7]      -881.193011
C(Bank)[T.1]           10.209208
C(Bank)[T.2]          113.451005
C(Bank)[T.3]           12.262071
C(Credit)[T.1]         93.447430
C(Credit)[T.2]        147.167069
C(Credit)[T.3]         76.376233
C(Vacation)[T.1]      449.105592
C(Period)[T.2]        -65.521781
C(Period)[T.3]       -118.036375
C(ChineseNY)[T.1]   -1418.213517
dtype: float64

In [11]:
# 預測

In [12]:
predictions = model.predict(data_predict).round()

# Output

In [13]:
data_predict['Prediction'] = predictions
data_predict

,Year,Month,Day,Weekday,Bank,Credit,Vacation,Period,ChineseNY,Prediction
0,2020,4,1,3,3,3,0,1,0,2124.0
1,2020,4,6,1,1,1,1,1,0,2864.0
2,2020,4,7,2,2,2,0,1,0,2328.0
3,2020,4,8,3,3,3,0,1,0,2124.0
4,2020,4,9,4,0,0,0,1,0,1906.0
5,2020,4,10,5,0,1,0,1,0,1975.0
6,2020,4,13,1,0,2,0,2,0,2393.0
7,2020,4,14,2,0,3,0,2,0,2078.0
8,2020,4,15,3,0,1,0,2,0,2064.0
9,2020,4,16,4,1,2,0,2,0,1998.0
10,2020,4,17,5,2,3,0,2,0,2005.0
11,2020,4,20,1,3,1,0,2,0,2352.0
12,2020,4,21,2,0,2,0,3,0,2096.0
13,2020,4,22,3,0,3,0,3,0,1994.0
14,2020,4,23,4,0,0,0,3,0,1788.0
15,2020,4,24,5,0,0,0,3,0,1763.0
16,2020,4,27,1,1,1,0,3,0,2297.0
17,2020,4,28,2,2,2,0,3,0,2210.0
18,2020,4,29,3,3,3,0,3,0,2006.0
19,2020,4,30,4,0,1,0,3,0,1882.0

In [14]:
# 抓取Simulation資料進來
simulation = pd.read_csv('simulation.csv', encoding = 'utf-8')
simulation

,Time,Mon,Mon-Inbound,Tue,Tue-Inbound,Wed,Wed-Inbound,Thur,Thur-Inbound,Fri,Fri-Inbound
0,9.0,32,164,27,136,28,138,28,133,26,123
1,9.5,29,147,25,128,25,123,25,120,26,117
2,10.0,30,157,29,138,28,138,26,128,25,122
3,10.5,33,167,31,139,32,139,30,139,28,131
4,11.0,31,156,27,134,29,139,28,138,26,122
5,11.5,31,147,28,126,28,126,25,120,26,115
6,12.0,24,102,20,87,21,84,21,79,19,80
7,12.5,21,87,19,78,19,74,18,69,18,65
8,13.0,24,98,20,87,22,91,20,85,20,86
9,13.5,30,131,25,116,24,112,25,109,27,111
10,14.0,30,139,29,128,28,125,28,117,25,114
11,14.5,29,139,26,124,27,119,23,111,25,118
12,15.0,30,135,27,119,25,121,27,115,24,111
13,15.5,27,128,28,126,26,117,24,108,25,112
14,16.0,28,126,26,115,24,110,25,107,25,107
15,16.5,24,115,24,111,24,111,22,101,23,94
16,17.0,20,91,19,84,19,85,18,78,17,75
17,17.5,18,67,18,62,19,63,18,63,17,60
18,18.0,16,51,15,50,15,50,14,44,14,41
19,18.5,14,44,13,41,13,40,12,36,13,33
20,19.0,14,39,13,39,13,38,13,35,12,28
21,19.5,15,45,14,41,14,41,12,34,11,28
22,20.0,13,41,13,40,12,34,11,32,10,26
23,20.5,12,34,12,35,11,31,11,28,10,22

In [15]:
time = simulation['Time'].tolist()

In [16]:
# Count Mon - Sun
day = ['Mon-Inbound', 'Tue-Inbound', 'Wed-Inbound', 'Thur-Inbound', 'Fri-Inbound', 'Fri-Inbound', 'Fri-Inbound']
col = simulation.columns.tolist()
count = 0
for i in range(0, len(col)):
    for j in range(0, len(day)):
        
        if col[i] == day[j]:
            day[j] = simulation[col[i]].sum()
day

[2550, 2284, 2249, 2129, 2041, 2041, 2041]

In [17]:
# 找乘數
a = data_predict['Year'].tolist()
mode = []
for i in range(0, len(a)):
    for j in range(0, len(day)):
        if data_predict['Weekday'][i] - 1 == j:
            result = data_predict['Prediction'][i] / day[j]
            mode.append(result)
data_predict['Mode'] = mode
data_predict

,Year,Month,Day,Weekday,Bank,Credit,Vacation,Period,ChineseNY,Prediction,Mode
0,2020,4,1,3,3,3,0,1,0,2124.0,0.944420
1,2020,4,6,1,1,1,1,1,0,2864.0,1.123137
2,2020,4,7,2,2,2,0,1,0,2328.0,1.019264
3,2020,4,8,3,3,3,0,1,0,2124.0,0.944420
4,2020,4,9,4,0,0,0,1,0,1906.0,0.895256
5,2020,4,10,5,0,1,0,1,0,1975.0,0.967663
6,2020,4,13,1,0,2,0,2,0,2393.0,0.938431
7,2020,4,14,2,0,3,0,2,0,2078.0,0.909807
8,2020,4,15,3,0,1,0,2,0,2064.0,0.917741
9,2020,4,16,4,1,2,0,2,0,1998.0,0.938469
10,2020,4,17,5,2,3,0,2,0,2005.0,0.982362
11,2020,4,20,1,3,1,0,2,0,2352.0,0.922353
12,2020,4,21,2,0,2,0,3,0,2096.0,0.917688
13,2020,4,22,3,0,3,0,3,0,1994.0,0.886616
14,2020,4,23,4,0,0,0,3,0,1788.0,0.839831
15,2020,4,24,5,0,0,0,3,0,1763.0,0.863792
16,2020,4,27,1,1,1,0,3,0,2297.0,0.900784
17,2020,4,28,2,2,2,0,3,0,2210.0,0.967601
18,2020,4,29,3,3,3,0,3,0,2006.0,0.891952
19,2020,4,30,4,0,1,0,3,0,1882.0,0.883983

In [18]:
# Need's columns
a = data_predict['Day'].tolist()

b = data_predict['Day'].astype(str).tolist()

In [28]:
col = data_predict['Day'].tolist()
col.insert(0, '')

coln = data_predict['Day'].tolist()
coln.insert(0, '')
col

['', 1, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 27, 28, 29, 30]

In [20]:
for i in range(0, len(a)):
    weekday = (data_predict['Weekday'][data_predict['Day'] == a[i]]).tolist()[0]
    if weekday == 1:
        b[i] = simulation['Mon'].tolist()
        
    if weekday == 2:
        b[i] = simulation['Tue'].tolist()
    if weekday == 3:
        b[i] = simulation['Wed'].tolist()
    if weekday == 4:
        b[i] = simulation['Thur'].tolist()
    if weekday == 5:
        b[i] = simulation['Fri'].tolist()
    if weekday == 6:
        b[i] = simulation['Fri'].tolist()
    if weekday == 7:
        b[i] = simulation['Fri'].tolist()
    for j in range(0, len(b[i])):
        b[i][j] = round(int(b[i][j]) * data_predict['Mode'][data_predict['Day'] == a[i]].tolist()[0] / 0.9)

In [30]:
for i in range(0, len(col)):
    if i == 0:
        col[i] = simulation['Time'].tolist()
    else:
        col[i] = b[i - 1]
col

[[9.0,
  9.5,
  10.0,
  10.5,
  11.0,
  11.5,
  12.0,
  12.5,
  13.0,
  13.5,
  14.0,
  14.5,
  15.0,
  15.5,
  16.0,
  16.5,
  17.0,
  17.5,
  18.0,
  18.5,
  19.0,
  19.5,
  20.0,
  20.5],
 [29,
  26,
  29,
  34,
  30,
  29,
  22,
  20,
  23,
  25,
  29,
  28,
  26,
  27,
  25,
  25,
  20,
  20,
  16,
  14,
  14,
  15,
  13,
  12],
 [40,
  36,
  37,
  41,
  39,
  39,
  30,
  26,
  30,
  37,
  37,
  36,
  37,
  34,
  35,
  30,
  25,
  22,
  20,
  17,
  17,
  19,
  16,
  15],
 [31,
  28,
  33,
  35,
  31,
  32,
  23,
  22,
  23,
  28,
  33,
  29,
  31,
  32,
  29,
  27,
  22,
  20,
  17,
  15,
  15,
  16,
  15,
  14],
 [29,
  26,
  29,
  34,
  30,
  29,
  22,
  20,
  23,
  25,
  29,
  28,
  26,
  27,
  25,
  25,
  20,
  20,
  16,
  14,
  14,
  15,
  13,
  12],
 [28,
  25,
  26,
  30,
  28,
  25,
  21,
  18,
  20,
  25,
  28,
  23,
  27,
  24,
  25,
  22,
  18,
  18,
  14,
  12,
  13,
  12,
  11,
  11],
 [28,
  28,
  27,
  30,
  28,
  28,
  20,
  19,
  22,
  29,
  27,
  27,
  26,
  27,
  27,
  25,
  18,
  18,
  15,
  14,
  13,
  12,
  11,
  11],
 [33,
  30,
  31,
  34,
  32,
  32,
  25,
  22,
  25,
  31,
  31,
  30,
  31,
  28,
  29,
  25,
  21,
  19,
  17,
  15,
  15,
  16,
  14,
  13],
 [27,
  25,
  29,
  31,
  27,
  28,
  20,
  19,
  20,
  25,
  29,
  26,
  27,
  28,
  26,
  24,
  19,
  18,
  15,
  13,
  13,
  14,
  13,
  12],
 [29,
  25,
  29,
  33,
  30,
  29,
  21,
  19,
  22,
  24,
  29,
  28,
  25,
  27,
  24,
  24,
  19,
  19,
  15,
  13,
  13,
  14,
  12,
  11],
 [29,
  26,
  27,
  31,
  29,
  26,
  22,
  19,
  21,
  26,
  29,
  24,
  28,
  25,
  26,
  23,
  19,
  19,
  15,
  13,
  14,
  13,
  11,
  11],
 [28,
  28,
  27,
  31,
  28,
  28,
  21,
  20,
  22,
  29,
  27,
  27,
  26,
  27,
  27,
  25,
  19,
  19,
  15,
  14,
  13,
  12,
  11,
  11],
 [33,
  30,
  31,
  34,
  32,
  32,
  25,
  22,
  25,
  31,
  31,
  30,
  31,
  28,
  29,
  25,
  20,
  18,
  16,
  14,
  14,
  15,
  13,
  12],
 [28,
  25,
  30,
  32,
  28,
  29,
  20,
  19,
  20,
  25,
  30,
  27,
  28,
  29,
  27,
  24,
  19,
  18,
  15,
  13,
  13,
  14,
  13,
  12],
 [28,
  25,
  28,
  32,
  29,
  28,
  21,
  19,
  22,
  24,
  28,
  27,
  25,
  26,
  24,
  24,
  19,
  19,
  15,
  13,
  13,
  14,
  12,
  11],
 [26,
  23,
  24,
  28,
  26,
  23,
  20,
  17,
  19,
  23,
  26,
  21,
  25,
  22,
  23,
  21,
  17,
  17,
  13,
  11,
  12,
  11,
  10,
  10],
 [25,
  25,
  24,
  27,
  25,
  25,
  18,
  17,
  19,
  26,
  24,
  24,
  23,
  24,
  24,
  22,
  16,
  16,
  13,
  12,
  12,
  11,
  10,
  10],
 [32,
  29,
  30,
  33,
  31,
  31,
  24,
  21,
  24,
  30,
  30,
  29,
  30,
  27,
  28,
  24,
  20,
  18,
  16,
  14,
  14,
  15,
  13,
  12],
 [29,
  27,
  31,
  33,
  29,
  30,
  22,
  20,
  22,
  27,
  31,
  28,
  29,
  30,
  28,
  26,
  20,
  19,
  16,
  14,
  14,
  15,
  14,
  13],
 [28,
  25,
  28,
  32,
  29,
  28,
  21,
  19,
  22,
  24,
  28,
  27,
  25,
  26,
  24,
  24,
  19,
  19,
  15,
  13,
  13,
  14,
  12,
  11],
 [28,
  25,
  26,
  29,
  28,
  25,
  21,
  18,
  20,
  25,
  28,
  23,
  27,
  24,
  25,
  22,
  18,
  18,
  14,
  12,
  13,
  12,
  11,
  11]]

In [31]:
# Output dataframe

Need = pd.DataFrame(data = col)

Ne = Need.T
Ne.columns = coln

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,...,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5
1,29.0,26.0,29.0,34.0,30.0,29.0,22.0,20.0,23.0,25.0,...,25.0,25.0,20.0,20.0,16.0,14.0,14.0,15.0,13.0,12.0
2,40.0,36.0,37.0,41.0,39.0,39.0,30.0,26.0,30.0,37.0,...,35.0,30.0,25.0,22.0,20.0,17.0,17.0,19.0,16.0,15.0
3,31.0,28.0,33.0,35.0,31.0,32.0,23.0,22.0,23.0,28.0,...,29.0,27.0,22.0,20.0,17.0,15.0,15.0,16.0,15.0,14.0
4,29.0,26.0,29.0,34.0,30.0,29.0,22.0,20.0,23.0,25.0,...,25.0,25.0,20.0,20.0,16.0,14.0,14.0,15.0,13.0,12.0
5,28.0,25.0,26.0,30.0,28.0,25.0,21.0,18.0,20.0,25.0,...,25.0,22.0,18.0,18.0,14.0,12.0,13.0,12.0,11.0,11.0
6,28.0,28.0,27.0,30.0,28.0,28.0,20.0,19.0,22.0,29.0,...,27.0,25.0,18.0,18.0,15.0,14.0,13.0,12.0,11.0,11.0
7,33.0,30.0,31.0,34.0,32.0,32.0,25.0,22.0,25.0,31.0,...,29.0,25.0,21.0,19.0,17.0,15.0,15.0,16.0,14.0,13.0
8,27.0,25.0,29.0,31.0,27.0,28.0,20.0,19.0,20.0,25.0,...,26.0,24.0,19.0,18.0,15.0,13.0,13.0,14.0,13.0,12.0
9,29.0,25.0,29.0,33.0,30.0,29.0,21.0,19.0,22.0,24.0,...,24.0,24.0,19.0,19.0,15.0,13.0,13.0,14.0,12.0,11.0
10,29.0,26.0,27.0,31.0,29.0,26.0,22.0,19.0,21.0,26.0,...,26.0,23.0,19.0,19.0,15.0,13.0,14.0,13.0,11.0,11.0
11,28.0,28.0,27.0,31.0,28.0,28.0,21.0,20.0,22.0,29.0,...,27.0,25.0,19.0,19.0,15.0,14.0,13.0,12.0,11.0,11.0
12,33.0,30.0,31.0,34.0,32.0,32.0,25.0,22.0,25.0,31.0,...,29.0,25.0,20.0,18.0,16.0,14.0,14.0,15.0,13.0,12.0
13,28.0,25.0,30.0,32.0,28.0,29.0,20.0,19.0,20.0,25.0,...,27.0,24.0,19.0,18.0,15.0,13.0,13.0,14.0,13.0,12.0
14,28.0,25.0,28.0,32.0,29.0,28.0,21.0,19.0,22.0,24.0,...,24.0,24.0,19.0,19.0,15.0,13.0,13.0,14.0,12.0,11.0
15,26.0,23.0,24.0,28.0,26.0,23.0,20.0,17.0,19.0,23.0,...,23.0,21.0,17.0,17.0,13.0,11.0,12.0,11.0,10.0,10.0
16,25.0,25.0,24.0,27.0,25.0,25.0,18.0,17.0,19.0,26.0,...,24.0,22.0,16.0,16.0,13.0,12.0,12.0,11.0,10.0,10.0
17,32.0,29.0,30.0,33.0,31.0,31.0,24.0,21.0,24.0,30.0,...,28.0,24.0,20.0,18.0,16.0,14.0,14.0,15.0,13.0,12.0
18,29.0,27.0,31.0,33.0,29.0,30.0,22.0,20.0,22.0,27.0,...,28.0,26.0,20.0,19.0,16.0,14.0,14.0,15.0,14.0,13.0
19,28.0,25.0,28.0,32.0,29.0,28.0,21.0,19.0,22.0,24.0,...,24.0,24.0,19.0,19.0,15.0,13.0,13.0,14.0,12.0,11.0
20,28.0,25.0,26.0,29.0,28.0,25.0,21.0,18.0,20.0,25.0,...,25.0,22.0,18.0,18.0,14.0,12.0,13.0,12.0,11.0,11.0

In [23]:
Ne.to_csv('Need.csv', index = 0, encoding = 'utf-8_sig')